abstract: Obfuscated HTML email addresses that look normal
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: HTML-Email-Obfuscate
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Parser: 2.25
  perl: 5.005
version: 1.00
